toshimaru/jekyll-toc

- README.md
- jekyll-toc.gemspec
- lib/jekyll-toc.rb
- lib/version.rb
- test/test_helper.rb
- test/test_inject_anchors_filter.rb
- test/test_toc_filter.rb
- test/test_toc_only_filter.rb
- test/test_toc_parser.rb
The existing filter `toc` got split up into one for generating just the TOC container and a second for injecting the HTML anchors into the content.
Also added some basic tests.
fixes #5 and partially #3
> Add new filters `toc_only` and `inject_anchors` to split up existing filter

- jekyll-toc.gemspec
- lib/table_of_contents/parser.rb
- test/test_kramdown_list.rb
- test/test_various_toc_html.rb
Issue #25 
- Add last_ul_used arguments to fix invalid nested `<ul>` tag
- Add more complex toc test
- Add [kramdown](https://github.com/gettalong/kramdown) list parser test for reference 
```html
<h6>h6</h6>
<h5>h5</h5>
<h4>h4</h4>
<h3>h3</h3>
<h2>h2</h2>
<h1>h1</h1>
```
This headings generate following TOC.
```html
<ul class="section-nav">
<li class="toc-entry toc-h6"><a href="#h6">h6</a></li>
<li class="toc-entry toc-h5"><a href="#h5">h5</a></li>
<li class="toc-entry toc-h4"><a href="#h4">h4</a></li>
<li class="toc-entry toc-h3"><a href="#h3">h3</a></li>
<li class="toc-entry toc-h2"><a href="#h2">h2</a></li>
<li class="toc-entry toc-h1"><a href="#h1">h1</a></li>
</ul>
```
---
```html
<h1>h1</h1>
<h3>h3</h3>
<h2>h2</h2>
<h4>h4</h4>
<h5>h5</h5>
```
This headings generate following TOC. …
> Fix invalid nested ul

- lib/jekyll-toc.rb
- lib/table_of_contents/parser.rb
- test/test_kramdown_list.rb
- test/test_various_toc_html.rb
Issue #31
jekyll-toc is now configurable by `_config.yml`!
You can configure heading min level and max level. (default heading levels are `h1` to `h6`)
`_config.yml`:
```yml
toc:
min_level: 1
max_level: 5
```
> TOC configuration: configurable heading min_level and max_level

- README.md
- lib/version.rb
closes #31 
v0.5.0 (from v0.5.0.rc) release. It contains configurable TOC heading feature and README update.
- README update
- Bump version
> V0.5.0 release: configurable heading min_level and max_level

- lib/table_of_contents/parser.rb
If _config.yml does not contain a `toc` section, `toc_config` will return nil, which breaks the parser. This is a potential fix.
> Fix toc_config being nil

- lib/table_of_contents/parser.rb
- lib/version.rb
- test/test_helper.rb
Fixes #37 by ignoring heading entries with class "no_toc" (the same class name used by Kramdown's TOC feature).
cc @Sfshaza @filiph @kwalrath
> Add support for no_toc

- README.md
- lib/table_of_contents/parser.rb
- lib/version.rb
- test/test_various_toc_html.rb
Adds an `ignore_within` option to provide a selector to ignore elements within. So given the following HTML:
```html
<h1>h1</h1>
<div class="exclude">
<h2>h2</h2>
<h3>h3</h3>
</div>
<h4>h4</h4>
```
With the configuration:
```yml
toc:
ignore_within: .exclude
```
All headings within the `.exclude` selector will be ignored.
> Add an `ignore_within` option

- lib/table_of_contents/parser.rb
- lib/version.rb
- test/test_various_toc_html.rb
Use the ID of the heading element as the anchor if it is present.
> Use explicit ID attribute if present

- README.md
- lib/table_of_contents/parser.rb
- test/test_various_toc_html.rb
Follow up to #53 
- Change option key name: ignore_within => no_toc_section_class
- Update README
- Fix issue: Elements inside `no_toc_section` are lost
> Add `no_toc_section` feature

- .rubocop.yml
- .travis.yml
- Appraisals
- jekyll-toc.gemspec
- lib/jekyll-toc.rb
- lib/table_of_contents/parser.rb
- lib/version.rb
- test/test_helper.rb
- test/test_kramdown_list.rb
- test/test_option_error.rb
- test/test_various_toc_html.rb
> Require Ruby 2.3+ / Nokogiri 1.8+

- README.md
- lib/table_of_contents/parser.rb
- test/test_various_toc_html.rb
> Allow mutiple `no_toc_section_class`es

- test/test_jekyll-toc.rb
> Test against PR: #77

- README.md
- lib/jekyll-toc.rb
- test/test_jekyll-toc.rb
- test/test_toc_tag.rb
Issue #38
- [Tags | Jekyll • Simple, blog-aware, static sites](https://jekyllrb.com/docs/plugins/tags/)
- [liquid/tag_unit_test.rb at master · Shopify/liquid](https://github.com/Shopify/liquid/blob/master/test/unit/tag_unit_test.rb)
> Liquid::Template.register_tag 'toc'

- Gemfile
- LICENSE.md
- gemfiles/jekyll_3.7.gemfile
- gemfiles/jekyll_3.8.gemfile
- gemfiles/jekyll_4.0.gemfile
- jekyll-toc.gemspec
- Year update: 2019 -> 2020
- Add jekyll as jekyll-toc runtime dependency
> Add Jekyll gem as a runtime_dependency

- lib/table_of_contents/configuration.rb
- lib/table_of_contents/helper.rb
- lib/table_of_contents/parser.rb
- test/parser/test_invalid_options.rb
- test/parser/test_various_toc_html.rb
closes #95, closes  #101
<details>
<summary>BEFORE</summary>
href inside toc:
```html
<li class="toc-entry toc-h1"><a href="#あ">あ</a>
```
href inside the anchor:
```html
<a class="anchor" href="#%E3%81%82" aria-hidden="true"> ...あ
```
</details>
<details>
<summary>AFTER</summary>
href inside toc:
```html
<li class="toc-entry toc-h1"><a href="#%E3%81%82">あ</a>
```
href inside the anchor:
```html
<a class="anchor" href="#%E3%81%82" aria-hidden="true"> ...あ
```
</details>
- `CGI.escape` for URL-encoding
- Refactoring: Create Helper module
- Refactoring: Do not use `Nokogiri::HTML(parser.toc)`, use `parser.build_toc` instead
> URL-Encoding for anchor link inside toc

- README.md
- lib/table_of_contents/configuration.rb
- lib/table_of_contents/parser.rb
- test/parser/test_ordered_list.rb
- test/test_configuration.rb
- test/test_helper.rb
By default `jekyll-toc` generates the HTML using unordered lists. If users desire ordered lists for their table of contents they cannot do so easily. With the changes below, the default behavior of using unordered lists will remain. However a new configuration option will toggle between `<ul></ul>` and `<ol></ol>` tags accordingly.
With the changes, users can add the existing custom classes to the top level heading and sub-headings separately. That way they can style the top heading and sub-headings separately. In this pass, I did not add the functionality to style multiple nested sub-headings but rather just all sub-headings using the existing configuration. If we feel that this would be useful, we can extend the current logic in the PR to inject classes similar to the list items so end …
> Add configuration to enable ordered list

- README.md
- lib/table_of_contents/configuration.rb
- lib/table_of_contents/parser.rb
- test/parser/test_ordered_list.rb
- test/test_configuration.rb
Follow up #117 . closes #71
Based on https://github.com/toshimaru/jekyll-toc/pull/117#pullrequestreview-483034489, I added some changes:
- `use_ordered_list` -> `ordered_list `
- Memorize list_tag method
> Ordered list support

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/rubocop.yml
- Configure GitHub Actions dependabot 
- Use actions/setup-ruby instead of eregon/use-ruby-action
> Configure GitHub Actions dependabot / Use actions/setup-ruby

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/rubocop.yml
- jekyll-toc.gemspec
- lib/table_of_contents/version.rb
Closes #139
- Use ruby/setup-ruby and support Ruby 3
- Drop Jekyll v3.8
- Drop Ruby v2.4
> Support Ruby 3 / Drop Jekyll v3.8 / Drop Ruby v2.4

- test/test_jekyll-toc.rb
- test/test_toc_tag.rb
ruby 3.2 changes Struct.new behavior so that keyword_init option is enabled by default. This means that keyword argument passed to the initializer of Struct is now treated differently with ruby3.2.
To avoid behavior change in jekyll-toc test code, use hash explicitly for Struct initializer.
Closes #164 .
> test: use hash explicitly for Struct initializer for ruby 3.2

- test/parser/test_invalid_options.rb
- test/parser/test_toc_filter.rb
- test/parser/test_various_toc_html.rb
- test/test_jekyll-toc.rb
- test/test_toc_tag.rb
Fix rubocop errors by running:
```console
$ bundle exec rubocop -a
```
> chore: Fix rubocop errors

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/rubocop.yml
Let's support Ruby 3.2.
closes #162
- CI against Ruby 3.2
- cherry-pick commits in #162.
- Use Ruby 3.2 for coverage and rubocop
> Test against Ruby 3.2

- .github/workflows/ci.yml
- .rubocop.yml
- Appraisals
- gemfiles/jekyll_3.9.gemfile
- gemfiles/jekyll_4.0.gemfile
- gemfiles/jekyll_4.2.gemfile
- gemfiles/jekyll_4.3.gemfile
- jekyll-toc.gemspec
- Drop Ruby 2.5 support
- CI against Jekyll 4.3
- Refactoring `gemspec` file
> Drop Ruby 2.5 support / CI against Jekyll 4.3 / Refactoring `gemspec` file
